#
# PHP 7 Dockerfile
#
# https://github.com/phalcon/dockerfiles
#

# Pull base image
FROM phalconphp/php-base

MAINTAINER Serghei Iakovlev <serghei@phalconphp.com>

RUN phpenv global 7.0.5

# Set up the command arguments
ENTRYPOINT ["php"]
CMD ["-v"]
